{% set name = "Flask-BabelEx" %}
{% set version = "0.9.4" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "39a59ccee9386a9d52d80b9101224402036aedc2c7873b11deef6e4e21cace27" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - flask
    - babel >=1.0
    - speaklater >=1.2
    - jinja2 >=2.5

test:
  imports:
    - flask_babelex

about:
  home: http://github.com/mrjoes/flask-babelex
  license_fine: LICENSE
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Adds i18n/l10n support to Flask applications'
  dev_url: http://github.com/mrjoes/flask-babelex

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
