travis:
  secure:
    BINSTAR_TOKEN: owkgSK7dXczzLv5dOh1rwUTjroHmFoHwdlqJI0qhh9fqwqBQbd0/kOmHt3dNJOmGpBEPMijoqa8i0CkCePEajPf3e89tUfyToavpnHlWWmP05hQl3TIx9wjZuW8Xf9Qhbw4FQYrKABQHIkLvPhJL4HARpGgJ6plxeIZwaTtqtccXPeVZ1X9syMx4A2aU8xqMDr9S0EwpDTEtL1Xv7tvv3xuS3H5SRbkgAmSvoyAN95WZwPM+aThNEKS9pCAkd1AS6R4IXItx9OXdkigzWDrIE6wXC67DQ0dufmDrQ7gZB5X1zfICLTPelpMzMyis9w/U3rhvbF15h2aEUeUeSQqd4RY02qa9ssvNLcfxmgCrGrLO3TNHc69thid5Ma5lBO2kVO9hTKZmKb1iaoPJaEsG1U4uwKA3ZTmF4MCIeh3vABAlFKA0uhUygAvvP16MLO++zo5H/pEJZkqNd8qsi9JYPnJFjAQqF7RWnwwimM+6WrO2y2FILU8G8RDiO0YczBWvz2uwgLRax+MRZCdcci80L0DYHLmaE75AiQn7NnyjLAG21Wv8x/zq939VeZVwX662PMoll/ONWRUXfZcP3wK9YwS5O9PAuwwL2NBTnLQyKrN6NuPUJwmtbKHq10HGenXKvWHFuN4kce4zHDitDHP+qpomgpfSVzZudZ/G4npbW44=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
