travis:
  secure:
    BINSTAR_TOKEN: JwSo/LtN8n4PnrMs7YTINNvGEyyzjy/Orxa1JByuXPlIS3wUbVGQwK01WlsBYf4WRmoB8BBHGZnflqkC0OVywueE8txHiqY/2oeZdU2ehymPCwKDR+O4QIhCxyVKI0F63CAgwoWlpElql+/J6e7H+meRhJpRqdaaN/DWeSJ3Zi3rnD7EMEVIMU5UNC2yernsxafZqWVrb8Z2ZwfS/ajO7X697RAgia2qacwztq1Kz/zy7h/XGBvMtXZfeWoqRr6j1QhcTQLsdc08H6PfZj4jpzxByXvjZVsnpLYC4fhupTmBzq419P0Jih1VCODX5t0nNGfmUwNUzhXVIJw8jcQApawvSxQIfaW7HuQUE/cZWLpECc7fjbuWxrVnGTh6yh/vE6yVDdHNx4/GlvD5QNER/9sw9mWBp+48No89dGV6PVinYpL44DFv/SXSAm0lrYhsMA2lVg+amZeHvtxBuftQg7doMVwVNPn5gZ4/HtrRqYHoWGKS69Di7RgcUW4uLXOFGSMTRuhViZybc5+94yhlDndz58soy9n9cgOdHw4yBMURS6/OEVhHIaVh4vDozIM9jOHaqpqPds6dL3hfx74L9UGBEWZXoEzQ4wol8OZVPuja/aXdGh8zgmvjpmP0kCfD0cN62BxGgcF9MF7kivpvEQz8maIj7d65sBY3kuhbeB4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
