travis:
  secure:
    BINSTAR_TOKEN: gA1pzhclka3Bavu4a6T5iaRzYFxTw5baMKE0mozS7MWtYtS4gHWaq4miR3vILJOxc0ycVuf4bXMZOBe0A9D87ExuIcCFyk5f0RBgRfUq38zcFUv8rXCgPGMN3QCYTlE67cpubMZFMUAndQNK5cRaKKCrdkwVOTQ7fXCgkes2b0Gs6/MOwdJvxCI+nWaYuKXXV9FaGBv3V15R13ktts+xVuqTP+IdA1GVVrqLcb8u4BlZvXX2oGe9aVW8F2PYSr7NqkHRe1+TQFlr59zFC7aBYAvCSfrZDEUttQyE5tlckKF5KUKo/y9vpbQnCW9ZsYUUN0AYRaLy5QY6/iYP3LrVkUglZYUOBPE581tR4tEH5ELejOc6T1LEJXFnZDlSYVOhzY9/7GMiZNLVc74YLRP9CfCOoxNcu+YEw+jL+PNp6In3WiOGSM3T+a15vR8ZxyPj1JDLuSHQ52AOC1KeSkX3E+kpeANTLKz7k3eyeA3C6v4XD32fk/hkKUulIxdequzesK7k75DqY7izorrqSmgSkorFnpHHCz/OeW6XzwoNB5RHUBhxJ4dIO4m1GZzCwKK/bIY/OGK22w10bEICwHZF936EcJV6+Nemz426sY0nXIm0fcRvMRY9BbTIPWBsoPTgLmKQHXiY0iBBuRIQp9kAyAewoJW2hu1qpM0WsJ8lnic=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
