travis:
  secure:
    BINSTAR_TOKEN: TuAKOgqosnRUXalLAVqUk91t+xxuCiGBdHiE8aYO8DFVxBsEVXzFCmSZjUwWBjMqwdw1HIE3a7X9hzazCeZJt0eZYELsBX4rBRfJmczFO/wyuXF04z9WqK+ZfwwnW7v1nSK9i2kjDFeJLM0XmZkH82Y3mR/FNuPWoJ51p07lljoo7DoihrFk3fNabzf7Cy+oq2agZn5DE1qQoYXiWSd2QVRB5MPo4X6wikYtaKDGJMbtLnQwnVgvnyqBZAtF0XL0Qw4dY3QiA19k+c11gjbCFrAwpYYQVCWDVLF3OTkhs9RkTjWYgFac/PjqifWs3su/ukjxvm1WM1qW+Z1nN3tkSA0DZMh/uePuLhf9FkoDiWSXPu4/JY1QVyPPaSD+QsVdrV7nCS+p5lKxd8wuWS7XUSh6xx46ygqxyueKGipSZaldzwlTxuV7tfF+7bgDve29Zvg3TQeQSJrgvogGiQMF2fK7EZb9PNUMtXaSTAzMFB+9OgXaMwYxM1f/TCOovmtSe4g/hpQk86sBj+aNpSosV+erV2WA54tj/clKwlOGoKsZgbkr07yaavCMAy7ziOCej70QxP471TgzQl37JvfCEiSVz/x/DpnB+ZsvP4OazyGPmJL7UfCx0pP7dQEQbyR9n9gKAJ/efObgbO42nsMhHURns4/jztfbhMX31iBK/vE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
